---
- name: Delete RDS and EC2 Instances
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Delete RDS Instance
    rds_instance:
      db_instance_identifier: wordpressappdb
      region: us-east-1
      state: absent
      skip_final_snapshot: true
    register: rds_result

  - name: Delete EC2 Instance
    ec2:
      instance_tags:
        Name: WebAppServer
      state: absent
    register: ec2_result

  - name: Display RDS Deletion Result
    debug:
      var: rds_result

  - name: Display EC2 Deletion Result
    debug:
      var: ec2_result
